name: cognoma-cancer-data
channels:
- conda-forge
dependencies:
- conda-forge::ipykernel=4.8.1
- conda-forge::jupyter=1.0.0
- conda-forge::nb_conda_kernels=2.1.0
- conda-forge::numexpr=2.6.0
- conda-forge::numpy=1.11.1
- conda-forge::pandas=0.18.1
- conda-forge::python=3.5.2
- conda-forge::seaborn=0.7.1
